//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.18 at 07:33:15 PM EEST 
//


package ua.nure.shevchenko.SummaryTask3.entity;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Bank complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Bank">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Type" type="{http://nure.ua/shevchenko/SummaryTask3/entity}Types"/>
 *         &lt;element name="Depositor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AccountId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="AmountOnDeposit" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="Profitability" type="{http://nure.ua/shevchenko/SummaryTask3/entity}Profit"/>
 *         &lt;element name="TimeConstraints" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Bank", propOrder = {
    "name",
    "country",
    "type",
    "depositor",
    "accountId",
    "amountOnDeposit",
    "profitability",
    "timeConstraints"
})
public class Bank {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Country", required = true)
    protected String country;
    @XmlElement(name = "Type", required = true)
    @XmlSchemaType(name = "string")
    protected Types type;
    @XmlElement(name = "Depositor", required = true)
    protected String depositor;
    @XmlElement(name = "AccountId")
    protected int accountId;
    @XmlElement(name = "AmountOnDeposit", required = true)
    protected BigDecimal amountOnDeposit;
    @XmlElement(name = "Profitability", required = true)
    protected BigDecimal profitability;
    @XmlElement(name = "TimeConstraints", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeConstraints;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link Types }
     *     
     */
    public Types getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link Types }
     *     
     */
    public void setType(Types value) {
        this.type = value;
    }

    /**
     * Gets the value of the depositor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositor() {
        return depositor;
    }

    /**
     * Sets the value of the depositor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositor(String value) {
        this.depositor = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     */
    public int getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     */
    public void setAccountId(int value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the amountOnDeposit property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAmountOnDeposit() {
        return amountOnDeposit;
    }

    /**
     * Sets the value of the amountOnDeposit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAmountOnDeposit(BigDecimal value) {
        this.amountOnDeposit = value;
    }

    /**
     * Gets the value of the profitability property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getProfitability() {
        return profitability;
    }

    /**
     * Sets the value of the profitability property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setProfitability(BigDecimal value) {
        this.profitability = value;
    }

    /**
     * Gets the value of the timeConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeConstraints() {
        return timeConstraints;
    }

    /**
     * Sets the value of the timeConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeConstraints(XMLGregorianCalendar value) {
        this.timeConstraints = value;
    }

}
